version: "3"
services:
  web:
    image: tristenps/aturian_meilisearch_example:latest
    ports:
      - "8080:3100"
    depends_on:
      - "meili"

  meili:
    image: getmeili/meilisearch
    ports:
      - "8081:7700"
    volumes:
      - ./data.ms:/data.ms
