version: "3"
services:
  web:
    # build: .
    image: node_meili_web:latest
    ports:
      - "8080:3100"
    depends_on:
      - "meili"
    command: []

  meili:
    image: getmeili/meilisearch
    ports:
      - "8081:7700"
    volumes:
      - ./data.ms:/data.ms
