version: "3"
services:
  web:
    # image: tristenps/aturian_meilisearch_example:latest
    image: local/node_meili
    ports:
      - "8080:3100"
    depends_on:
      - "meili"
    environment:
      - NODE_ENV=production
      - PORT=3100
      - MEILI_DOCKER_URL=http://meili:7700

  meili:
    image: getmeili/meilisearch
    ports:
      - "8081:7700"
    volumes:
      - ./data.ms:/data.ms
