version: "3"
services:
  web:
    build: .
    ports:
      - "8080:3100"
    depends_on:
      - "meili"
    environment:
      - NODE_ENV=production
      - PORT=3100
      - MEILI_DOCKER_URL=http://meili:7700
      - MEILI_MASTER_KEY=1234
      - SALT=ABC

  meili:
    image: getmeili/meilisearch:v0.16.0
    ports:
      - "7700:7700"
    volumes:
      - ./data.ms:/data.ms
    environment:
      - MEILI_MASTER_KEY=1234
      - MEILI_ENV=production
